services:
  nginx:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80