apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx
  namespace: nginx-lab 
  labels:
    app:  nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  nginx
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  nginx
        image:  nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: nginx
              key: DB_HOST
        ports:
        - containerPort:  80
          name:  nginx
        volumeMounts:
        # - name: localtime
        #   mountPath: /etc/localtime
        # - name: nginx-config
        #   mountPath: /etc/nginx/conf.d/default.conf
        - name: nginx-site
          mountPath: /usr/share/nginx/html
          readOnly: true
        securityContext:
          fsGroup: 0
      volumes:
        # - name: localtime
        #   hostPath:
        #     path: /usr/share/zoneinfo/Europe/Riga
        # - name: nginx-config
        #   hostPath:
        #     path: /home/ange/sgt-k8s-2023/docker.nginx/default.conf
        #     type: File
        - name: nginx-site
          hostPath:
            path: /home/ange/sgt-k8s-2023/docker.nginx/html
      restartPolicy: Always